

# -------------------------------------------------------------------------------------
# Multilingual and i18n | 多语言 i18n
# See: https://gohugo.io/content-management/multilingual/#configure-languages
# -------------------------------------------------------------------------------------

weight = 2
# language directory
# 语言目录
#contentDir = "content/zh-cn"
title = "高阶无穷郝"
# language code, only CN capitalized here
# 网站语言，仅在这里 CN 大写
# language code ["en", "zh-CN", "fr", "pl", ...]
# language name ["English", "简体中文", "Français", "Polski", ...]
languageCode = "zh-CN"
# language name
# 语言名称
languageName = "简体中文"
# whether to include Chinese/Japanese/Korean
# 是否包括中日韩文字
hasCJKLanguage = true
# copyright description used only for seo schema
# 版权描述，仅用于 SEO
copyright = "本站内容采用 CC BY-NC-SA 4.0 国际许可协议。"


[params.author]
name = "Hao"
email = "mkdirhao@qq.com"
link = ""
avatar = "/icon.svg"
[params.page]
endFlag = "转载请注明出处,附上原文链接即可 "
[params.page.reward]
      enable = true
      animation = true
      # position relative to post footer, optional values: ["before", "after"]
      position = "before"
      
      comment = "Buy me a coffee or 来一碗老北京豆汁"
      # comment = "Buy me a coffee"
      # FixIt 0.2.18 | NEW display mode of QR code images, optional values: ["static", "fixed"], default: `static`
      mode = "fixed"
      [params.page.reward.ways]
       wechatpay = "/images/wechat.jpg"
       alipay = "/images/alipay.jpg"
        # wechatpay = "/images/wechatpay.png"
        # alipay = "/images/alipay.png"
        # paypal = "/images/paypal.png"
        # bitcoin = "/images/bitcoin.png"
[params.social]
 Youtubechannel = ""

# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[menu]
  [[menu.main]]             # config your menu              # 配置目录
  name = "主页"
  weight = 1
  url = "/"
  [menu.main.params]
      icon = "fa-solid fa-home"
  [[menu.main]]
    identifier = "archives"
    parent = ""
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "归档"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 2
    # FixIt 0.2.14 | NEW add user-defined content to menu items
    [menu.main.params]
      # add css class to a specific menu item
      class = ""
      # whether set as a draft menu item whose function is similar to a draft post/page
      draft = false
      # FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
      icon = "fa-solid fa-archive"
      # FixIt 0.2.16 | NEW set menu item type, optional values: ["mobile", "desktop"]
      type = ""
  [[menu.main]]
    identifier = "categories"
    parent = "archives"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-folder-tree"
   [[menu.main]]
    identifier = "all"
    parent = "archives"
    pre = ""
    post = ""
    name = "所有文章"
    url = "/posts/"
    title = ""
    weight = 2
    [menu.main.params]
      icon = "fa-solid fa-archive"
  [[menu.main]]
    identifier = "tags"
    parent = "archives"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 5
    [menu.main.params]
      icon = "fa-solid fa-tags"
  [[menu.main]]
    identifier = "collections"
    parent = "archives"
    pre = ""
    post = ""
    name = "合集"
    url = "/collections/"
    title = ""
    weight = 4
    [menu.main.params]
      icon = "fa-solid fa-layer-group"
  [[menu.main]]
    identifier = "about"
    parent = ""
    pre = ""
    post = ""
    name = "是我"
    url = "/about/"
    title = ""
    weight = 100
    [menu.main.params]
      icon = "fa-solid fa-heart"
   
