# -------------------------------------------------------------------------------------
# Multilingual and i18n | 多语言 i18n
# See: https://gohugo.io/content-management/multilingual/#configure-languages
# -------------------------------------------------------------------------------------

weight = 1
# language directory
# 语言目录
#contentDir = "content/en"
# language code
# 网站语言
# language code ["en", "zh-CN", "fr", "pl", ...]
# language name ["English", "简体中文", "Français", "Polski", ...]
languageCode = "en"
# language name
# 语言名称
languageName = "English"
# whether to include Chinese/Japanese/Korean
# 是否包括中日韩文字
hasCJKLanguage = false
# copyright description used only for seo schema
# 版权描述，仅用于 SEO
copyright = "This work is licensed under CC BY-NC-SA-4.0."


# -------------------------------------------------------------------------------------
# Menu Configuration
# See: https://fixit.lruihao.cn/documentation/basics/#menu-configuration
# -------------------------------------------------------------------------------------

[menu]
  [[menu.main]]             # config your menu              # 配置目录
  name = "Home"
  weight = 1
  url = "/"
  [menu.main.params]
      icon = "fa-solid fa-home"
  [[menu.main]]
    identifier = "archives"
    parent = ""
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Archives"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 2
    # FixIt 0.2.14 | NEW add user-defined content to menu items
    [menu.main.params]
      # add css class to a specific menu item
      class = ""
      # whether set as a draft menu item whose function is similar to a draft post/page
      draft = false
      # FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
      icon = "fa-solid fa-archive"
      # FixIt 0.2.16 | NEW set menu item type, optional values: ["mobile", "desktop"]
      type = ""
  [[menu.main]]
    identifier = "categories"
    parent = "archives"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-folder-tree"
   [[menu.main]]
    identifier = "all"
    parent = "archives"
    pre = ""
    post = ""
    name = "All article"
    url = "/posts/"
    title = ""
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-archive"
  [[menu.main]]
    identifier = "tags"
    parent = "archives"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 5
    [menu.main.params]
      icon = "fa-solid fa-tags"
  [[menu.main]]
    identifier = "collections"
    parent = "archives"
    pre = ""
    post = ""
    name = "Collections"
    url = "/collections/"
    title = ""
    weight = 4
    [menu.main.params]
      icon = "fa-solid fa-layer-group"
  [[menu.main]]
    identifier = "about"
    parent = ""
    pre = ""
    post = ""
    name = "It's me"
    url = "/about/"
    title = ""
    weight = 100
    [menu.main.params]
      icon = "fa-solid fa-heart"
   
 # Header config
  [params.header]
    # FixIt 0.2.13 | CHANGED desktop header mode ["sticky", "normal", "auto"]
    desktopMode = "sticky"
    # FixIt 0.2.13 | CHANGED mobile header mode ["sticky", "normal", "auto"]
    mobileMode = "auto"
    # Header title config
    [params.header.title]
      # URL of the LOGO
      logo = "/icon.svg"
      # title name
      name = "mkdirHao"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # whether to use typeit animation for title name
      typeit = false
    # FixIt 0.2.12 | NEW Header subtitle config
    [params.header.subtitle]
      # subtitle name
      name = "forever young"
      # whether to use typeit animation for subtitle name
      typeit = true
  # Home page config
  [params.home]
    # amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = "mkdirhao@qq.com"
      # URL of avatar shown in home page
      avatarURL = "/icon.svg"
      # FixIt 0.2.17 | NEW identifier of avatar menu link
      avatarMenu = ""
      # title shown in home page (HTML format is supported)
      title = "mkdirHao"
      # subtitle shown in home page
      subtitle = "in spring flowers grow \n in autumn the moon glows\n in summer breezes blow \n in winter it snows \n when nothing bothers you \nthat’s the best time of life"
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # disclaimer (HTML format is supported)
      disclaimer = "If there are different opinions, you are right.👍"
    # Home page posts
    [params.home.posts]
      enable = true
      # special amount of posts in each home posts page
      paginate = 6
  [params.page.reward]
      enable = true
      animation = true
      # position relative to post footer, optional values: ["before", "after"]
      position = "before"
      
      comment = "Buy me a coffee "
      # comment = "Buy me a coffee"
      # FixIt 0.2.18 | NEW display mode of QR code images, optional values: ["static", "fixed"], default: `static`
      mode = "fixed"
      [params.page.reward.ways]
       wechatpay = "/images/wechat.jpg"
       alipay = "/images/alipay.jpg"
        # wechatpay = "/images/wechatpay.png"
        # alipay = "/images/alipay.png"
        paypal = "/images/paypal.png"
        # bitcoin = "/images/bitcoin.png"
  [params.author]
    name = "hao"
    email = "mkdirhao@qq.com"
    link = ""
    avatar = "/icon.svg"
  [params.social]
    Paypal = "mkdirhao"