# -------------------------------------------------------------------------------------
# Multilingual and i18n | 多语言 i18n
# See: https://gohugo.io/content-management/multilingual/#configure-languages
# -------------------------------------------------------------------------------------

title = "mkdirHao'Blog"

#site description
description = "mkdirHao'blog-高阶无穷郝的博客,a blog about web development, programming, and life in tokyo | 一个关于web开发、编程和东京生活的博客"
# site keywords
keywords = [
    "mkdirHao",
    "高阶无穷郝",
    "博客",
    "blog",
    "web development",
    "web开发",
    "programming",
    "编程",
    "life in tokyo",
    "东京生活",
]


weight = 1
# language directory
# 语言目录
#contentDir = "content/en"
# language code
# 网站语言
languageCode = "en"
# language name
# 语言名称
languageName = "English"
# whether to include Chinese/Japanese/Korean
# 是否包括中日韩文字
hasCJKLanguage = false
# copyright description used only for seo schema
# 版权描述，仅用于 SEO
copyright = "This work is licensed under CC BY-NC-SA-4.0."
