[context.production.environment]
  HUGO_VERSION = "0.134.2"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.134.2"

# Show a custom 404 for this path
[[redirects]]
from = "/en/*"
to = "/en/404.html"
status = 404

[[redirects]]
from = "/ja/*"
to = "/ja/404.html"
status = 404

[[redirects]]
from = "/zh-cn/*"
to = "/zh-cn/404.html"
status = 404

[[redirects]]
from = "/*"
to = "/en/404.html"
status = 404
